<?xml version="1.0"?>
<robot name="car" xmlns:xacro="http://ros.org/wiki/xacro">


<!-- ===== Global Parameters ===== -->

<xacro:property name="car_length" value="0.3762" />             <!-- x axis  -->
<xacro:property name="car_width" value="0.2124" />              <!-- y axis  -->
<xacro:property name="car_height" value="0.0762" />              <!-- z axis  -->
<xacro:property name="wheel_radius" value="0.0508" />
<xacro:property name="wheel_length" value="0.0508" />

<xacro:property name="capota_car_length" value="0.2746" />             <!-- x axis  -->
<xacro:property name="capota_car_width" value="0.2124" />              <!-- y axis  -->
<xacro:property name="capota_car_height" value="0.0508" />              <!-- z axis  -->

<!-- Material do carrinho em si -->
<material name="green">
  <color rgba="0 1 0 1"/>
</material>
<!-- Material da caporta -->
<material name="light_green">
  <color rgba="0.1 1 0.2 1"/>
</material>
<!-- Material  das rodas -->
<material name="yellow">
  <color rgba="1 1 0 1"/>
</material>

  

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x y roll">
    <link name="${prefix}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="yellow"/>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x} ${y} ${-car_height/2}" rpy="${roll} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>






  <!-- Construções -->


  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${car_length} ${car_width} ${car_height}"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>
  
  <!-- capota -->
  <link name="capota">
    <visual>
      <geometry>
        <box size="${capota_car_length} ${capota_car_width} ${capota_car_height}"/>
      </geometry>
      <material name="light_green"/>
    </visual>
  </link>
  <joint name="capota_joint" type="fixed">
    <parent link="base_link"/>
    <child link="capota"/>
    <origin xyz="${capota_car_length/2-car_length/2} 0 ${car_height/2+capota_car_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <!-- 4 rodas -->
  <xacro:wheel prefix="front_left" x="${car_length/2}" y="${car_width/2+wheel_length/2}" roll="${pi/2}"/>
  <xacro:wheel prefix="front_right" x="${car_length/2}" y="${-car_width/2-wheel_length/2}" roll="${pi/2}"/>
  <xacro:wheel prefix="back_left" x="${-car_length/2}" y="${+car_width/2+wheel_length/2}" roll="${pi/2}"/>
  <xacro:wheel prefix="back_right" x="${-car_length/2}" y="${-car_width/2-wheel_length/2}" roll="${pi/2}"/>

</robot>
