# PID Gains for gazebo_ros_control (must be at root level)
gazebo_ros_control:
  pid_gains:
    front_left_wheel_joint:
      p: 100.0
      i: 1.0
      d: 10.0
    front_right_wheel_joint:
      p: 100.0
      i: 1.0
      d: 10.0
    back_left_wheel_joint:
      p: 100.0
      i: 1.0
      d: 10.0
    back_right_wheel_joint:
      p: 100.0
      i: 1.0
      d: 10.0

# Controller configurations (under /car namespace)
car:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  front_left_steering_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 1.0, d: 10.0}
  
  front_right_steering_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 1.0, d: 10.0}