# PID Gains - must match exactly the joint names from URDF
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel:  ['back_left_wheel_joint']
  right_wheel: ['back_right_wheel_joint']
  wheel_separation: 0.3  # Adjust
  wheel_radius: 0.05     # Adjust
  cmd_vel_topic: cmd_vel  # Must match teleop's topic
  
gazebo_ros_control:
  pid_gains:
    # front_left_wheel_joint: {p: 100.0, i: 1.0, d: 10.0}
    # front_right_wheel_joint: {p: 100.0, i: 1.0, d: 10.0,}
    back_left_wheel_joint: {p: 10.0, i: 0.1, d: 0.0,}
    back_right_wheel_joint: {p: 10.0, i: 0.1, d: 0.0,}

# Controller configurations
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# front_left_steering_controller:
#   type: effort_controllers/JointPositionController
#   joint: front_left_wheel_joint

# front_right_steering_controller:
#   type: effort_controllers/JointPositionController
#   joint: front_right_wheel_joint

back_left_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_left_wheel_joint

back_right_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_right_wheel_joint